### 1. Register cashback rule
POST {{accrual_server_address}}/api/goods
Content-Type: application/json

{
  "match": "LG",
  "reward": 5,
  "reward_type": "%"
}

### 2. Create order to count cashback
POST {{accrual_server_address}}/api/orders
Content-Type: application/json

{
  "order": "123455",
  "goods": [
    {
      "description": "LG Monitor",
      "price": 50000.0
    }
  ]
}

### 3. Get orders cashback
GET {{accrual_server_address}}/api/orders/123455

### 4. Register user
POST {{server_address}}/api/user/register
Content-Type: application/json; charset=UTF-8

{
  "login": "apricot",
  "password": "1"
}

### 5. Login user
POST {{server_address}}/api/user/login
Content-Type: application/json; charset=UTF-8

{
  "login": "apricot",
  "password": "1"
}

### 6. Add order to program
POST {{server_address}}/api/user/orders
Content-Type: text/plain; charset=UTF-8
# a number must be verified with Luhn algorithm

123455

### 7. Get user's orders status
GET {{server_address}}/api/user/orders

### 8. Get user's balance
GET {{server_address}}/api/user/balance

### 9. Add withdrawal
POST {{server_address}}/api/user/balance/withdraw
Content-Type: application/json; charset=UTF-8

{
	"order": "2377225624",
    "sum": 751
}

### 10. Get current user balance
GET {{server_address}}/api/user/balance/withdrawals
